# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AI agent → relay: route encrypted decisions to registered user devices.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteDecision = channel.unary_unary(
                '/noxy.agent.AgentService/RouteDecision',
                request_serializer=agent__pb2.RouteDecisionRequest.SerializeToString,
                response_deserializer=agent__pb2.DeliveryOutcome.FromString,
                _registered_method=True)
        self.GetDecisionOutcome = channel.unary_unary(
                '/noxy.agent.AgentService/GetDecisionOutcome',
                request_serializer=agent__pb2.GetDecisionOutcomeRequest.SerializeToString,
                response_deserializer=agent__pb2.GetDecisionOutcomeResponse.FromString,
                _registered_method=True)
        self.GetQuota = channel.unary_unary(
                '/noxy.agent.AgentService/GetQuota',
                request_serializer=agent__pb2.GetQuotaRequest.SerializeToString,
                response_deserializer=agent__pb2.GetQuotaResponse.FromString,
                _registered_method=True)
        self.GetIdentityDevices = channel.unary_unary(
                '/noxy.agent.AgentService/GetIdentityDevices',
                request_serializer=agent__pb2.GetIdentityDevicesRequest.SerializeToString,
                response_deserializer=agent__pb2.GetIdentityDevicesResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AI agent → relay: route encrypted decisions to registered user devices.
    """

    def RouteDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecisionOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentityDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteDecision,
                    request_deserializer=agent__pb2.RouteDecisionRequest.FromString,
                    response_serializer=agent__pb2.DeliveryOutcome.SerializeToString,
            ),
            'GetDecisionOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecisionOutcome,
                    request_deserializer=agent__pb2.GetDecisionOutcomeRequest.FromString,
                    response_serializer=agent__pb2.GetDecisionOutcomeResponse.SerializeToString,
            ),
            'GetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuota,
                    request_deserializer=agent__pb2.GetQuotaRequest.FromString,
                    response_serializer=agent__pb2.GetQuotaResponse.SerializeToString,
            ),
            'GetIdentityDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentityDevices,
                    request_deserializer=agent__pb2.GetIdentityDevicesRequest.FromString,
                    response_serializer=agent__pb2.GetIdentityDevicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noxy.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noxy.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AI agent → relay: route encrypted decisions to registered user devices.
    """

    @staticmethod
    def RouteDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.agent.AgentService/RouteDecision',
            agent__pb2.RouteDecisionRequest.SerializeToString,
            agent__pb2.DeliveryOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecisionOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.agent.AgentService/GetDecisionOutcome',
            agent__pb2.GetDecisionOutcomeRequest.SerializeToString,
            agent__pb2.GetDecisionOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.agent.AgentService/GetQuota',
            agent__pb2.GetQuotaRequest.SerializeToString,
            agent__pb2.GetQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentityDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.agent.AgentService/GetIdentityDevices',
            agent__pb2.GetIdentityDevicesRequest.SerializeToString,
            agent__pb2.GetIdentityDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
