# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import noxy_pb2 as noxy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in noxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PushServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushNotification = channel.unary_unary(
                '/noxy.push.PushService/PushNotification',
                request_serializer=noxy__pb2.PushNotificationRequest.SerializeToString,
                response_deserializer=noxy__pb2.PushResponse.FromString,
                _registered_method=True)
        self.GetQuota = channel.unary_unary(
                '/noxy.push.PushService/GetQuota',
                request_serializer=noxy__pb2.GetQuotaRequest.SerializeToString,
                response_deserializer=noxy__pb2.GetQuotaResponse.FromString,
                _registered_method=True)
        self.GetIdentityDevices = channel.unary_unary(
                '/noxy.push.PushService/GetIdentityDevices',
                request_serializer=noxy__pb2.GetIdentityDevicesRequest.SerializeToString,
                response_deserializer=noxy__pb2.GetIdentityDevicesResponse.FromString,
                _registered_method=True)


class PushServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentityDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PushServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.PushNotification,
                    request_deserializer=noxy__pb2.PushNotificationRequest.FromString,
                    response_serializer=noxy__pb2.PushResponse.SerializeToString,
            ),
            'GetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuota,
                    request_deserializer=noxy__pb2.GetQuotaRequest.FromString,
                    response_serializer=noxy__pb2.GetQuotaResponse.SerializeToString,
            ),
            'GetIdentityDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentityDevices,
                    request_deserializer=noxy__pb2.GetIdentityDevicesRequest.FromString,
                    response_serializer=noxy__pb2.GetIdentityDevicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noxy.push.PushService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noxy.push.PushService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PushService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.push.PushService/PushNotification',
            noxy__pb2.PushNotificationRequest.SerializeToString,
            noxy__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.push.PushService/GetQuota',
            noxy__pb2.GetQuotaRequest.SerializeToString,
            noxy__pb2.GetQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentityDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noxy.push.PushService/GetIdentityDevices',
            noxy__pb2.GetIdentityDevicesRequest.SerializeToString,
            noxy__pb2.GetIdentityDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
