# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noxy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'noxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnoxy.proto\x12\tnoxy.push\"\x91\x01\n\x17PushNotificationRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nciphertext\x18\x02 \x01(\x0c\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\r\x12\x18\n\x10target_device_id\x18\x04 \x01(\t\x12\x10\n\x08kyber_ct\x18\x05 \x01(\x0c\x12\r\n\x05nonce\x18\x06 \x01(\x0c\"M\n\x0cPushResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.noxy.push.DeliveryStatus\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"%\n\x0fGetQuotaRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x8e\x01\n\x10GetQuotaResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x13\n\x0bquota_total\x18\x03 \x01(\x04\x12\x17\n\x0fquota_remaining\x18\x04 \x01(\x04\x12&\n\x06status\x18\x05 \x01(\x0e\x32\x16.noxy.push.QuotaStatus\"D\n\x19GetIdentityDevicesRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bidentity_id\x18\x02 \x01(\t\"N\n\x0eIdentityDevice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x15\n\rpq_public_key\x18\x03 \x01(\x0c\"\\\n\x1aGetIdentityDevicesResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12*\n\x07\x64\x65vices\x18\x02 \x03(\x0b\x32\x19.noxy.push.IdentityDevice*T\n\x0e\x44\x65liveryStatus\x12\r\n\tDELIVERED\x10\x00\x12\n\n\x06QUEUED\x10\x01\x12\x0e\n\nNO_DEVICES\x10\x02\x12\x0c\n\x08REJECTED\x10\x03\x12\t\n\x05\x45RROR\x10\x04*G\n\x0bQuotaStatus\x12\x10\n\x0cQUOTA_ACTIVE\x10\x00\x12\x13\n\x0fQUOTA_SUSPENDED\x10\x01\x12\x11\n\rQUOTA_DELETED\x10\x02\x32\x86\x02\n\x0bPushService\x12O\n\x10PushNotification\x12\".noxy.push.PushNotificationRequest\x1a\x17.noxy.push.PushResponse\x12\x43\n\x08GetQuota\x12\x1a.noxy.push.GetQuotaRequest\x1a\x1b.noxy.push.GetQuotaResponse\x12\x61\n\x12GetIdentityDevices\x12$.noxy.push.GetIdentityDevicesRequest\x1a%.noxy.push.GetIdentityDevicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERYSTATUS']._serialized_start=680
  _globals['_DELIVERYSTATUS']._serialized_end=764
  _globals['_QUOTASTATUS']._serialized_start=766
  _globals['_QUOTASTATUS']._serialized_end=837
  _globals['_PUSHNOTIFICATIONREQUEST']._serialized_start=26
  _globals['_PUSHNOTIFICATIONREQUEST']._serialized_end=171
  _globals['_PUSHRESPONSE']._serialized_start=173
  _globals['_PUSHRESPONSE']._serialized_end=250
  _globals['_GETQUOTAREQUEST']._serialized_start=252
  _globals['_GETQUOTAREQUEST']._serialized_end=289
  _globals['_GETQUOTARESPONSE']._serialized_start=292
  _globals['_GETQUOTARESPONSE']._serialized_end=434
  _globals['_GETIDENTITYDEVICESREQUEST']._serialized_start=436
  _globals['_GETIDENTITYDEVICESREQUEST']._serialized_end=504
  _globals['_IDENTITYDEVICE']._serialized_start=506
  _globals['_IDENTITYDEVICE']._serialized_end=584
  _globals['_GETIDENTITYDEVICESRESPONSE']._serialized_start=586
  _globals['_GETIDENTITYDEVICESRESPONSE']._serialized_end=678
  _globals['_PUSHSERVICE']._serialized_start=840
  _globals['_PUSHSERVICE']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
